version: '3.7'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - classic
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: music

  backend:
    build: .
    ports:
      - '8081:8080'
    env_file:
      - .env
    environment:
      DB_USER: root
      DB_PASSWORD: pass
      DB_URL: jdbc:postgresql://db:5432/music
    depends_on:
      - db
    networks:
      - classic

networks:
  classic:
    name: classic