server:
  port: 8080
spring:
  application:
    name: classic
  datasource:
    url: '${DB_URL}'
    username: '${DB_USER}'
    password: '${DB_PASSWORD}'
    driver-class-name: org.postgresql.Driver
springdoc:
  swagger-ui:
    path: /docs.html